### ISSUE TITLE
Make previous decoration disappear when switching workspaces/windows

### ISSUE THREAD

**Issue by geowarin** [moustacheful/glint#2]
Hello,

First of all, thank you for this nice tool, I really like it.
Customizing it with css is awesome.

I noticed that when you switch windows very quickly, they end up all having decorations which is a bit distracting but OK.
The issue is more pronounced when you have a window taking a part of your monitor, switch to it, then quickly change to another workspace containing a full screen window.

You'll end up seeing the frame of the half size window inside the full screen window whereas it is not even in the same workspace. Weird :)

Anyway, it's a small thing but I wonder if it would be possible to cancel the ongoing animation when switching windows.

**Comment by moustacheful** [comment]
Hey @geowarin thanks for trying it out!

I've made the change you requested because it makes sense. I had planned to actually control these via classes  in the future (so you could apply an 'out' transition if you wanted) but for now, lingering decorations are just annoying.
